<?php
declare(strict_types=1);

namespace core\players\forms;

use core\forms\formapi\CustomForm;
use core\main\text\TextFormat;
use pocketmine\player\Player;

class RegistrationForm extends CustomForm
{

    public function __construct(Player $player)
    {
        parent::__construct($this->getFormResultCallable());
        $this->setTitle(TextFormat::BOLD_GRAY . "Registration");
    }

    public function getFormResultCallable(): callable
    {
        parent::getFormResultCallable(); // TODO: Change the autogenerated stub
    }

}